/**
 * Tripartie Web API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelWebhook model module.
 * @module model/ModelWebhook
 * @version 1.0
 */
class ModelWebhook {
    /**
     * Constructs a new <code>ModelWebhook</code>.
     * @alias module:model/ModelWebhook
     */
    constructor() { 
        
        ModelWebhook.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelWebhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelWebhook} obj Optional instance to populate.
     * @return {module:model/ModelWebhook} The populated <code>ModelWebhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelWebhook();

            if (data.hasOwnProperty('eventType')) {
                obj['eventType'] = ApiClient.convertToType(data['eventType'], 'String');
            }
            if (data.hasOwnProperty('transactionTemplateExternalId')) {
                obj['transactionTemplateExternalId'] = ApiClient.convertToType(data['transactionTemplateExternalId'], 'String');
            }
            if (data.hasOwnProperty('transactionTemplateTripartieId')) {
                obj['transactionTemplateTripartieId'] = ApiClient.convertToType(data['transactionTemplateTripartieId'], 'Number');
            }
            if (data.hasOwnProperty('eventTimestamp')) {
                obj['eventTimestamp'] = ApiClient.convertToType(data['eventTimestamp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The webhook type.
 * @member {module:model/ModelWebhook.EventTypeEnum} eventType
 */
ModelWebhook.prototype['eventType'] = undefined;

/**
 * The Transaction template's External ID.
 * @member {String} transactionTemplateExternalId
 */
ModelWebhook.prototype['transactionTemplateExternalId'] = undefined;

/**
 * The Transaction template's Tripartie ID.
 * @member {Number} transactionTemplateTripartieId
 */
ModelWebhook.prototype['transactionTemplateTripartieId'] = undefined;

/**
 * The event timestamp.
 * @member {Number} eventTimestamp
 */
ModelWebhook.prototype['eventTimestamp'] = undefined;





/**
 * Allowed values for the <code>eventType</code> property.
 * @enum {String}
 * @readonly
 */
ModelWebhook['EventTypeEnum'] = {

    /**
     * value: "proposition_sent"
     * @const
     */
    "proposition_sent": "proposition_sent",

    /**
     * value: "proposition_accepted"
     * @const
     */
    "proposition_accepted": "proposition_accepted",

    /**
     * value: "proposition_rejected"
     * @const
     */
    "proposition_rejected": "proposition_rejected",

    /**
     * value: "transaction_completed"
     * @const
     */
    "transaction_completed": "transaction_completed",

    /**
     * value: "transaction_canceled"
     * @const
     */
    "transaction_canceled": "transaction_canceled"
};



export default ModelWebhook;

