/**
 * Tripartie Web API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelUser model module.
 * @module model/ModelUser
 * @version 1.0
 */
class ModelUser {
    /**
     * Constructs a new <code>ModelUser</code>.
     * @alias module:model/ModelUser
     */
    constructor() { 
        
        ModelUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelUser} obj Optional instance to populate.
     * @return {module:model/ModelUser} The populated <code>ModelUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The User's Tripartie ID.
 * @member {Number} id
 */
ModelUser.prototype['id'] = undefined;

/**
 * The User's External ID.
 * @member {String} externalId
 */
ModelUser.prototype['externalId'] = undefined;






export default ModelUser;

