/**
 * Tripartie Web API
 * This document describes all use cases offered by the Tripartie Web API.<br /><br /> The Tripartie Web API allows you to easily create Transaction templates.<br /> Those templates allows a User (the Buyer) to quickly initiate a Transaction pre-configured by another User (the Seller).<br /> This allows you to add a Secured Payment button on your website pages.<br /> To facilitate working with the Web API, we built libraries for common developpement environment.<br/><br/> You're reading the documentation for version 1.0 of the Web API.<br/> Go to version <select id=\"version-switcher\"></select> 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestRegisterUser model module.
 * @module model/RequestRegisterUser
 * @version 1.0
 */
class RequestRegisterUser {
    /**
     * Constructs a new <code>RequestRegisterUser</code>.
     * @alias module:model/RequestRegisterUser
     * @param email {String} The user's email.
     */
    constructor(email) { 
        
        RequestRegisterUser.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>RequestRegisterUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestRegisterUser} obj Optional instance to populate.
     * @return {module:model/RequestRegisterUser} The populated <code>RequestRegisterUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestRegisterUser();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The user's email.
 * @member {String} email
 */
RequestRegisterUser.prototype['email'] = undefined;

/**
 * The user's External ID.
 * @member {String} externalId
 */
RequestRegisterUser.prototype['externalId'] = undefined;

/**
 * The user's display name.
 * @member {String} displayName
 */
RequestRegisterUser.prototype['displayName'] = undefined;






export default RequestRegisterUser;

