/**
 * Tripartie Web API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TripartieWebAPI);
  }
}(this, function(expect, TripartieWebAPI) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TripartieWebAPI.ModelWebhook();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelWebhook', function() {
    it('should create an instance of ModelWebhook', function() {
      // uncomment below and update the code to test ModelWebhook
      //var instane = new TripartieWebAPI.ModelWebhook();
      //expect(instance).to.be.a(TripartieWebAPI.ModelWebhook);
    });

    it('should have the property eventType (base name: "eventType")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new TripartieWebAPI.ModelWebhook();
      //expect(instance).to.be();
    });

    it('should have the property transactionTemplateExternalId (base name: "transactionTemplateExternalId")', function() {
      // uncomment below and update the code to test the property transactionTemplateExternalId
      //var instance = new TripartieWebAPI.ModelWebhook();
      //expect(instance).to.be();
    });

    it('should have the property transactionTemplateTripartieId (base name: "transactionTemplateTripartieId")', function() {
      // uncomment below and update the code to test the property transactionTemplateTripartieId
      //var instance = new TripartieWebAPI.ModelWebhook();
      //expect(instance).to.be();
    });

    it('should have the property eventTimestamp (base name: "eventTimestamp")', function() {
      // uncomment below and update the code to test the property eventTimestamp
      //var instance = new TripartieWebAPI.ModelWebhook();
      //expect(instance).to.be();
    });

  });

}));
