/**
 * Tripartie Web API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@tripartie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Error from './model/Error';
import ModelTransactionTemplate from './model/ModelTransactionTemplate';
import ModelUser from './model/ModelUser';
import RequestCreateTransactionTemplate from './model/RequestCreateTransactionTemplate';
import RequestRegisterUser from './model/RequestRegisterUser';
import Webhook from './model/Webhook';
import TransactionTemplatesApi from './api/TransactionTemplatesApi';
import UsersApi from './api/UsersApi';
import WebhooksApi from './api/WebhooksApi';


/**
* .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TripartieWebAPI = require('index'); // See note below*.
* var xxxSvc = new TripartieWebAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TripartieWebAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TripartieWebAPI.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TripartieWebAPI.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ModelTransactionTemplate model constructor.
     * @property {module:model/ModelTransactionTemplate}
     */
    ModelTransactionTemplate,

    /**
     * The ModelUser model constructor.
     * @property {module:model/ModelUser}
     */
    ModelUser,

    /**
     * The RequestCreateTransactionTemplate model constructor.
     * @property {module:model/RequestCreateTransactionTemplate}
     */
    RequestCreateTransactionTemplate,

    /**
     * The RequestRegisterUser model constructor.
     * @property {module:model/RequestRegisterUser}
     */
    RequestRegisterUser,

    /**
     * The Webhook model constructor.
     * @property {module:model/Webhook}
     */
    Webhook,

    /**
    * The TransactionTemplatesApi service constructor.
    * @property {module:api/TransactionTemplatesApi}
    */
    TransactionTemplatesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WebhooksApi service constructor.
    * @property {module:api/WebhooksApi}
    */
    WebhooksApi
};
